### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by streamich** [csstree/validator#11]
Can this lib be used in a browser?

**Comment by lahmatiy** [comment]
Nope, at the monent, since it uses `fs` module.
What a use case do you have?

**Comment by streamich** [comment]
I want to create an addon for [`nano-css`](https://github.com/streamich/nano-css) that would automatically validate CSS and inform developer. Is there a lib you could recommend for that?

**Comment by lahmatiy** [comment]
This module is a wrapper for [CSSTree](https://github.com/csstree/csstree). You can use it for your purposes like that module does.

**Comment by revelt** [comment]
What if we separated CLI from the core (function which takes string and outputs plain object), then tapped that core in CLI, plus published the core using Rollup in CJS, ES Modules and UMD formats? Theoretically, people would be able to access that UMD build via browsers, maybe even straight from npm CDN's (for example, `<script src="https://cdn.jsdelivr.net/npm/email-comb/dist/email-comb.umd.js"></script>` of mine).

Another problem with this CLI being bundled is that when I consume this package, my Rollup complains about `path` and `fs` dependencies — but I don't even use them via `validateString()`! It's the bundled CLI that uses them, basically, all I need is `validateString()`.

<img width="774" alt="errors" src="https://user-images.githubusercontent.com/8344688/72535377-5c0bef00-3870-11ea-847f-c7cd233e2d34.png">

The benefit of this program is that it sugar-coats the AST traversal from people — which can cause brain haemorrhages for junior developers. Conceptually, it's genius: a function with string-in, array of zero or more error objects out.

It's just Rollup is needed and CLI must be separated.
