### ISSUE TITLE
[CSSTree] Unknown property `font-display`

### ISSUE THREAD

**Issue by personaaleatoria** [csstree/validator#17]
I am receiving this error message from the csstree vscode validator extension.

`[CSSTree] Unknown property 'font-display'`

For this code: `font-display: swap;`

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

**Comment by personaaleatoria** [comment]
the link says it's in 'working draft' but its well supported across browsers so shouldn't it be reconigized as valid by validator?

**Comment by lahmatiy** [comment]
That's because `font-display` is not a property but `@font-face` at-rule descriptor. With [2.0](https://github.com/csstree/validator/releases/tag/v2.0.0) validator now validate at-rules right, so it's not an issue anymore.
