### ISSUE TITLE
Marking as invalid browser properties

### ISSUE THREAD

**Issue by Zardoz89** [csstree/validator#28]
csstree validator marks browser prefix properties values as invalid : 

An example : 
```
# target/webapp-compress/css/main.css
    * Invalid value for `display` property
      syntax: [ <display-outside> || <display-inside> ] | <display-listitem> | <display-internal> | <display-box> | <display-legacy> | <-non-standard-display>
       value: -ms-flexbox
      --------^
    * Invalid value for `display` property
      syntax: [ <display-outside> || <display-inside> ] | <display-listitem> | <display-internal> | <display-box> | <display-legacy> | <-non-standard-display>
       value: -ms-flexbox
```
At least, should be ignored by a option of the validator.

**Comment by lahmatiy** [comment]
Please open an issue in [CSSTree tracker](https://github.com/csstree/csstree) if you still think it's relevant. It seems that the CSSTree dictionary is missing that keyword in the [`<-non-standard-display>`](https://csstree.github.io/docs/syntax/#Property:display) syntax.
