### ISSUE TITLE
Error on "text-rendering: optimizeLegibility;"

### ISSUE THREAD

**Issue by PavelFil** [csstree/validator#41]
For CSS property ```text-rendering: optimizeLegibility;``` in @font-face section the validator returns an error message.

**Comment by lahmatiy** [comment]
The descriptor is missed in CSSTree dictionary (and mdn-data as well). So we need to add it to its dictionary

**Comment by PavelFil** [comment]
> The descriptor is missed in CSSTree dictionary (and mdn-data as well). So we need to add it to its dictionary

It seems, the MDN has the descriptior https://developer.mozilla.org/en-US/docs/Web/CSS/text-rendering

**Comment by skyclouds2001** [comment]
> > The descriptor is missed in CSSTree dictionary (and mdn-data as well). So we need to add it to its dictionary
> 
> It seems, the MDN has the descriptior https://developer.mozilla.org/en-US/docs/Web/CSS/text-rendering

not really, the `@font-face/text-rendering` is not the same as `text-rendering`

and I doesn't find any evidence that this is supported, neither in https://drafts.csswg.org/css-fonts/#font-face-rule nor https://svgwg.org/svg2-draft/painting.html#TextRenderingProperty

just a question, are you sure that `@font-face/text-rendering` is supported?

**Comment by PavelFil** [comment]
@skyclouds2001 You are right. This page https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face doesn't have information about @font-face/text-rendering.
