### ISSUE TITLE
filter: progid:DXImageTransform.Microsoft.AlphaImageLoader

### ISSUE THREAD

**Issue by joseAndresGomezTovar** [csstree/validator#9]
Have you thought about supporting it? In some css it is used
> pure-css layout for example

**Comment by sideshowbarker** [comment]
Support for it was recently added to the W3C CSS Validator. See https://github.com/w3c/css-validator/pull/134 & https://github.com/w3c/css-validator/commit/ab64237ce24499bb0f8c23631135d18ee58cb96f — with a warning emitted to indicate that it’s a non-standard vendor extension.

So yeah I agree it’s be helpful to users to have it supported in CSSTree too

**Comment by joseAndresGomezTovar** [comment]
Thank you for your fast reply! @sideshowbarker 
This is the console.log output of reporter

```
  <?xml version="1.0" encoding="utf-8"?>
    <checkstyle version="4.3">
      <file name="./public/stylesheets/pricing.css">
        <error line="61" column="19" severity="error" message="Unexpected input" source="csstree-validator"/>
      </file>
  </checkstyle>
```


I would like to add a test using mocha+assert, What is the best way? This is my code

```
var check = function (file) {
   describe(file, function () {
      it('should be empty', function () {
         var tmp = validateFile(file);
         if (tmp[file].length != 0) console.log(reporter(validateFile(file)));
         assert.equal(tmp[file].length, 0)
      })
   })
};
```

**Comment by lahmatiy** [comment]
Coming back to this issue, it has been supported for a long time. But there are plans to remove support, because it is a legacy of IE6 - in this form the value did not work even in IE7, as I know.
